"""Integration agent: wires the generated frontend and backend together and reports what it found.

It is deterministic (no model): it reads the generated files, lists every API call the frontend makes,
matches them against the routes the backend defines, aligns environment variables and CORS, and writes the
full-stack README plus an INTEGRATION_REPORT.md.
"""

import re
from dataclasses import dataclass, field

from app.codegen.engine import GenFile
from app.codegen import widgets


@dataclass
class Check:
    name: str
    status: str  # pass | fail | warn | info
    detail: str = ""


@dataclass
class IntegrationReport:
    checks: list[Check] = field(default_factory=list)
    actions: list[str] = field(default_factory=list)
    calls: list[str] = field(default_factory=list)
    routes: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not any(c.status == "fail" for c in self.checks)

    def to_dict(self) -> dict:
        return {
            "ok": self.ok,
            "checks": [c.__dict__ for c in self.checks],
            "actions": self.actions,
            "calls": self.calls,
            "routes": self.routes,
        }


def _norm(path: str) -> str:
    path = re.sub(r"\$\{[^}]*\}", "{}", path)
    path = re.sub(r"\{[a-zA-Z_]+\}", "{}", path)
    return path.split("?")[0].rstrip("/") or "/"


FORM_ENDPOINTS = {"contact": "/api/contact", "booking": "/api/bookings", "subscription": "/api/subscribers"}


def frontend_calls(files: list[GenFile], project: dict | None = None) -> list[str]:
    """Endpoint paths the frontend requests (from the widget source files).

    The form widget carries all three form endpoints; only those for form kinds that are actually on the site count.
    """
    used_forms = {
        (n.get("variant") if n.get("variant") in FORM_ENDPOINTS else "contact")
        for pg in (project or {}).get("pages", [])
        for n in pg.get("tree", [])
        if n.get("type") == "forms"
    }
    skip = {path for kind, path in FORM_ENDPOINTS.items() if project is not None and kind not in used_forms}
    found: set[str] = set()
    for f in files:
        if "widgets/" not in f.path or not f.path.endswith(".tsx"):
            continue
        for m in re.finditer(r"`\$\{apiUrl\}(/api/[^`]*)`", f.content):
            found.add(_norm(m.group(1)))
        for m in re.finditer(r'"(/api/[a-z_/-]+)"', f.content):  # e.g. ENDPOINT map in FormWidget
            found.add(_norm(m.group(1)))
    return sorted(found - skip)


def backend_routes(files: list[GenFile]) -> list[str]:
    routes: set[str] = set()
    for f in files:
        if not f.path.startswith("backend/") or not f.path.endswith(".py"):
            continue
        prefix_match = re.search(r'APIRouter\(prefix="([^"]*)"', f.content)
        prefix = prefix_match.group(1) if prefix_match else ""
        for m in re.finditer(r'@router\.(?:get|post|put|patch|delete)\(\s*"([^"]*)"', f.content):
            routes.add(_norm(prefix + m.group(1)))
        # Flask / Django style
        for m in re.finditer(r'@api\.(?:get|post|put|patch|delete)\("([^"]*)"', f.content):
            routes.add(_norm("/api" + re.sub(r"<[a-z]+:[a-z_]+>", "{}", m.group(1))))
        for m in re.finditer(r'path\("([^"]+)"', f.content):
            routes.add(_norm("/api/" + re.sub(r"<[a-z]+:[a-z_]+>", "{}", m.group(1))))
    return sorted(routes)


def _has_backend(files: list[GenFile]) -> bool:
    return any(f.path.startswith("backend/") for f in files)


def _full_readme(project: dict, options, files: list[GenFile], report: IntegrationReport, has_backend: bool) -> str:
    name = project.get("name", "My Website")
    fe_cmd = {"nextjs": "npm run dev", "react": "npm run dev", "html": "open index.html in your browser (or use any static server)"}[options.framework]
    fe_url = {"nextjs": "http://localhost:3000", "react": "http://localhost:5173", "html": "file://"}[options.framework]
    env = widgets.env_name() if widgets.CTX["framework"] != "html" else ""
    pages = "\n".join(f"- `{p.get('path', '/')}` — {p.get('name', 'Page')}" for p in project.get("pages", []))
    comps = sorted({n.get("type", "") for p in project.get("pages", []) for n in p.get("tree", [])})
    backend_section = ""
    if has_backend:
        backend_section = f"""
## 2. Start the backend

```bash
cd backend
python -m venv .venv
source .venv/bin/activate        # Windows: .venv\\Scripts\\activate
pip install -r requirements.txt
cp .env.example .env             # then set ADMIN_API_KEY and JWT_SECRET
uvicorn app.main:app --reload     # API on http://localhost:8000  (docs at /docs)
```

Run the backend tests any time with `cd backend && pytest -q`.
"""
    return f"""# {name}

Generated by **VIBE**. This document explains how to run the whole project and how the pieces fit together.

## Project layout

```
{'frontend files ........ this folder (' + options.framework + ')' }
{'backend/ .............. Python API' if has_backend else ''}
INTEGRATION_REPORT.md ... what the integration agent checked
docs/REQUIREMENTS.md .... what this site was built to do (if provided)
```

## 1. Start the frontend

```bash
npm install
{'cp .env.example .env.local   # sets ' + env + '=http://localhost:8000' if env else ''}
{fe_cmd}
```

Open {fe_url}.
{backend_section}
## Pages
{pages}

## Components used
{', '.join(c for c in comps if c)}

## How the frontend and backend connect

{'The frontend reads `' + env + '` and sends JSON requests to the backend under `/api`. The backend allows the frontend origin through `CORS_ORIGINS` in `backend/.env`.' if has_backend else 'This export has no backend. Interactive widgets (shop, chat, forms) run in preview mode with sample data.'}

{'### API calls made by the frontend' if report.calls else ''}
{chr(10).join('- `' + c + '`' for c in report.calls)}

{'### Payments (Razorpay)' if any('/payments/razorpay' in c for c in report.calls) else ''}
{'Leave `RAZORPAY_KEY_ID` and `RAZORPAY_KEY_SECRET` empty in `backend/.env` to run in **mock mode** (no real charges, ideal for testing). For live payments add both keys and set `RAZORPAY_WEBHOOK_SECRET`, then point a Razorpay webhook at `/api/payments/razorpay/webhook`.' if any('/payments/razorpay' in c for c in report.calls) else ''}

## Before you go live

- Set strong values for `ADMIN_API_KEY` and `JWT_SECRET`.
- Use PostgreSQL or MySQL instead of SQLite for production.
- Restrict `CORS_ORIGINS` to your real domain.
- Review `INTEGRATION_REPORT.md` for anything marked as a warning.
"""


def integrate(files: list[GenFile], project: dict, options) -> tuple[list[GenFile], IntegrationReport]:
    report = IntegrationReport()
    has_backend = _has_backend(files)
    framework = options.framework
    calls = frontend_calls(files, project)
    routes = backend_routes(files) if has_backend else []
    report.calls, report.routes = calls, routes
    by_path = {f.path: f for f in files}

    # 1. contract: every call the frontend makes must exist on the backend
    if calls and not has_backend:
        report.checks.append(Check("Frontend has a backend to talk to", "info", "Widgets run in preview mode because no backend was generated."))
    for call in calls:
        matched = call in routes
        if has_backend:
            report.checks.append(Check(f"Frontend calls {call}", "pass" if matched else "fail", "Backend route exists" if matched else "No matching backend route"))

    # 2. environment variable + CORS alignment
    if calls:
        env_file = by_path.get(".env.example")
        env_name = widgets.env_name()
        ok_env = bool(env_file and env_name in env_file.content)
        report.checks.append(Check("Frontend knows the API address", "pass" if ok_env else "fail", f"{env_name} is set in .env.example" if ok_env else f"{env_name} missing"))
    if has_backend:
        origin = {"nextjs": "http://localhost:3000", "react": "http://localhost:5173", "html": "http://localhost:8080"}[framework]
        be_env = by_path.get("backend/.env.example")
        if be_env:
            m = re.search(r"^CORS_ORIGINS=(.*)$", be_env.content, re.M)
            current = [o.strip() for o in (m.group(1) if m else "").split(",") if o.strip()]
            if origin not in current:
                current.append(origin)
                be_env.content = re.sub(r"^CORS_ORIGINS=.*$", "CORS_ORIGINS=" + ",".join(current), be_env.content, flags=re.M)
                report.actions.append(f"Added {origin} to the backend CORS_ORIGINS so the browser is allowed to call the API.")
            report.checks.append(Check("Backend allows the frontend origin (CORS)", "pass", f"{origin} is allowed"))
        if any(f.path == "backend/app/shop.py" for f in files):
            report.checks.append(Check("Razorpay payments", "info", "Runs in mock mode until RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET are set."))
        report.checks.append(Check("Backend ships its own end-to-end tests", "pass" if "backend/tests/test_e2e.py" in by_path else "warn", "backend/tests/test_e2e.py" if "backend/tests/test_e2e.py" in by_path else "No tests were generated for this framework"))
        report.checks.append(Check("Connected forms", "pass", "Contact, booking and newsletter forms submit to the API") if any(n.get("type") == "forms" for p in project.get("pages", []) for n in p.get("tree", [])) else Check("Connected forms", "info", "No forms on the site"))
    if framework == "html" and any(n.get("type") in widgets.WIDGET_TYPES for p in project.get("pages", []) for n in p.get("tree", [])):
        report.checks.append(Check("Interactive widgets", "warn", "HTML export cannot run the shop, chat or tracking widgets. Export as Next.js or React."))

    # 3. docs
    requirements = (project.get("settings") or {}).get("docs", {})
    for path, key in (("docs/REQUIREMENTS.md", "requirements"), ("docs/ACCEPTANCE.md", "acceptance")):
        if requirements.get(key):
            files.append(GenFile(path, requirements[key]))
            report.actions.append(f"Included {path} from the intake conversation.")
    readme = _full_readme(project, options, files, report, has_backend)
    files[:] = [f for f in files if f.path != "README.md"] + [GenFile("README.md", readme)]
    report.actions.append("Wrote a full-stack README with start-up steps for the frontend and backend.")
    files.append(GenFile("INTEGRATION_REPORT.md", render_report(project, report)))
    return files, report


ICON = {"pass": "PASS", "fail": "FAIL", "warn": "WARN", "info": "INFO"}


def render_report(project: dict, report: IntegrationReport) -> str:
    lines = [f"# Integration report — {project.get('name', 'Project')}", "", f"Overall: **{'OK' if report.ok else 'NEEDS ATTENTION'}**", "", "## Checks", ""]
    lines += [f"- `{ICON[c.status]}` **{c.name}** {('— ' + c.detail) if c.detail else ''}" for c in report.checks]
    if report.actions:
        lines += ["", "## What the integration agent did", ""] + [f"- {a}" for a in report.actions]
    if report.routes:
        lines += ["", "## Backend routes", ""] + [f"- `{r}`" for r in report.routes]
    return "\n".join(lines) + "\n"
