import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  CircleHelp,
  ClipboardList,
  DollarSign,
  Eye,
  EyeOff,
  FileText,
  Grid2X2,
  LayoutTemplate,
  Megaphone,
  Menu,
  PackageSearch,
  MessagesSquare,
  Milestone,
  MessageSquareQuote,
  PanelBottom,
  Share2,
  PanelsTopLeft,
  Redo2,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Undo2,
  Users,
  WandSparkles,
} from "lucide-react";

export const COMPONENT_ICONS: Record<string, LucideIcon> = {
  navbar: Menu,
  hero: Sparkles,
  features: PanelsTopLeft,
  cards: Grid2X2,
  pricing: DollarSign,
  footer: PanelBottom,
  forms: ClipboardList,
  testimonials: MessageSquareQuote,
  cta: Megaphone,
  faq: CircleHelp,
  stats: BarChart3,
  team: Users,
  logoCloud: LayoutTemplate,
  banner: Megaphone,
  notifications: Megaphone,
  catalog: ShoppingBag,
  timeline: Milestone,
  socials: Share2,
  chatbot: MessagesSquare,
  shop: ShoppingCart,
  tracking: PackageSearch,
  icons: LayoutTemplate,
};

export { Eye, EyeOff, FileText, Redo2, Undo2, WandSparkles };
