import { cssVarsFor, fontsOf } from "./engine";
import { fontsUrl } from "./fonts";
import type { StyleSpec, StyleTokens } from "./types";

const ren = (vars: Record<string, string>) =>
  Object.entries(vars)
    .filter(([k]) => !k.startsWith("--s-bg-l"))
    .map(([k, v]) => `  ${k.replace("--s-", "--vibe-")}: ${v};`)
    .join("\n");

export function toFontImport(spec: StyleSpec) {
  return `/* Google Fonts */\n@import url("${fontsUrl(fontsOf(spec))}");\n\n<!-- or in <head> -->\n<link rel="preconnect" href="https://fonts.googleapis.com">\n<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n<link rel="stylesheet" href="${fontsUrl(fontsOf(spec))}">`;
}

export function toComponentCss(spec: StyleSpec) {
  const glass = spec.card === "glass" || spec.glass;
  const btn =
    spec.button === "outline" ? "background: transparent; color: var(--vibe-primary); border: max(var(--vibe-bw), 1.5px) solid var(--vibe-primary);"
    : spec.button === "gradient" ? "background: var(--vibe-grad); color: var(--vibe-on-primary); border: 0;"
    : spec.button === "tonal" ? "background: var(--vibe-primary-c); color: var(--vibe-on-primary-c); border: 0;"
    : spec.button === "brutal" ? "background: var(--vibe-accent); color: var(--vibe-on-accent); border: 3px solid var(--vibe-text); box-shadow: var(--vibe-shadow-1);"
    : "background: var(--vibe-primary); color: var(--vibe-on-primary); border: 0;";
  return `/* Component styles — generated by VIBE Style Studio */
.btn {
  ${btn}
  border-radius: var(--vibe-r-btn);
  padding: var(--vibe-sp-3) var(--vibe-sp-5);
  font: 600 var(--vibe-base)/1 var(--vibe-font-b);
  transition: transform var(--vibe-dur) var(--vibe-ease), box-shadow var(--vibe-dur) var(--vibe-ease);
}
.btn:hover { transform: translateY(var(--vibe-lift)) scale(var(--vibe-scale)); }
.btn:focus-visible { outline: none; box-shadow: var(--vibe-focus); }

.card {
  background: ${glass ? "var(--vibe-glass-bg)" : spec.card === "flat" ? "transparent" : "var(--vibe-surface)"};
  ${glass ? "backdrop-filter: blur(var(--vibe-glass-blur));" : ""}
  border: var(--vibe-bw) solid var(--vibe-outline);
  border-radius: var(--vibe-r-card);
  box-shadow: ${spec.card === "elevated" || spec.card === "brutal" || spec.card === "soft" ? "var(--vibe-shadow-2)" : "none"};
  padding: var(--vibe-sp-5);
  transition: transform var(--vibe-dur) var(--vibe-ease), box-shadow var(--vibe-dur) var(--vibe-ease);
}
.card:hover { transform: translateY(var(--vibe-lift)); }

.input {
  background: var(--vibe-bg);
  color: var(--vibe-text);
  border: max(var(--vibe-bw), 1px) solid var(--vibe-outline);
  border-radius: var(--vibe-r-input);
  padding: var(--vibe-sp-3) var(--vibe-sp-4);
  font: var(--vibe-base) var(--vibe-font-b);
}
.input:focus { outline: none; box-shadow: var(--vibe-focus); border-color: var(--vibe-primary); }

h1, h2, h3 { font-family: var(--vibe-font-h); font-weight: var(--vibe-w-h); letter-spacing: var(--vibe-track-h); text-transform: var(--vibe-transform); line-height: var(--vibe-lh-h); }
body { background: var(--vibe-bg); color: var(--vibe-text); font: var(--vibe-base)/var(--vibe-lh) var(--vibe-font-b); }
img { filter: var(--vibe-img-filter); }

@media (prefers-reduced-motion: reduce) { * { transition: none !important; animation: none !important; } }`;
}

export function toCss(spec: StyleSpec, tokens: StyleTokens) {
  const light = cssVarsFor(spec, tokens, "light");
  const dark = cssVarsFor(spec, tokens, "dark");
  return `/* VIBE design system — ${spec.name} · fingerprint generated locally */
${toFontImport(spec).split("\n\n")[0]}

:root {
${ren(light)}
}

:root[data-theme="dark"] {
${ren(dark)}
}

${toComponentCss(spec)}
`;
}

export function toTailwind(spec: StyleSpec, tokens: StyleTokens) {
  const c = (n: string) => `"var(--vibe-${n})"`;
  return `// tailwind.config.ts — generated by VIBE Style Studio (${spec.name})
import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: ["selector", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        background: ${c("bg")}, foreground: ${c("text")},
        surface: { DEFAULT: ${c("surface")}, variant: ${c("surface-2")} },
        primary: { DEFAULT: ${c("primary")}, foreground: ${c("on-primary")}, container: ${c("primary-c")} },
        secondary: { DEFAULT: ${c("secondary")}, foreground: ${c("on-secondary")} },
        accent: { DEFAULT: ${c("accent")}, foreground: ${c("on-accent")} },
        muted: ${c("muted")}, outline: ${c("outline")},
        success: ${c("success")}, warning: ${c("warning")}, error: ${c("error")},
      },
      fontFamily: { heading: [${c("font-h")}], sans: [${c("font-b")}], mono: [${c("font-m")}] },
      borderRadius: { sm: ${c("r-sm")}, md: ${c("r-md")}, lg: ${c("r-lg")}, xl: ${c("r-xl")}, button: ${c("r-btn")}, card: ${c("r-card")} },
      boxShadow: { 1: ${c("shadow-1")}, 2: ${c("shadow-2")}, 3: ${c("shadow-3")} },
      screens: { sm: "${tokens.breakpoints.sm}px", md: "${tokens.breakpoints.md}px", lg: "${tokens.breakpoints.lg}px", xl: "${tokens.breakpoints.xl}px" },
      maxWidth: { container: ${c("container")} },
      transitionDuration: { DEFAULT: ${c("dur")} },
      transitionTimingFunction: { DEFAULT: ${c("ease")} },
      fontSize: {
        xs: "${tokens.typography.sizes.xs}px", sm: "${tokens.typography.sizes.sm}px", base: "${tokens.typography.sizes.base}px", lg: "${tokens.typography.sizes.lg}px",
        xl: "${tokens.typography.sizes.xl}px", "2xl": "${tokens.typography.sizes["2xl"]}px", "3xl": "${tokens.typography.sizes["3xl"]}px", "4xl": "${tokens.typography.sizes["4xl"]}px",
      },
      spacing: { ${tokens.spacing.map((v, i) => `"s${i + 1}": "${v}px"`).join(", ")} },
    },
  },
} satisfies Config;
`;
}

export function toJson(spec: StyleSpec, tokens: StyleTokens) {
  const { fix, locks, ...rest } = spec;
  return JSON.stringify({ format: "vibe-style@1", spec: { ...rest, fix }, tokens }, null, 2);
}

export function download(filename: string, content: string, type = "text/plain") {
  const blob = new Blob([content], { type });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 1000);
}

export function shareLink(spec: StyleSpec) {
  const { fix, locks, ...rest } = spec;
  const b64 = btoa(unescape(encodeURIComponent(JSON.stringify(rest))));
  return `${location.origin}${location.pathname}#style=${b64}`;
}

export function parseShared(hash: string): StyleSpec | null {
  const m = /style=([^&]+)/.exec(hash);
  if (!m) return null;
  try {
    const obj = JSON.parse(decodeURIComponent(escape(atob(m[1]))));
    return { ...obj, fix: { light: {}, dark: {} }, locks: {} } as StyleSpec;
  } catch {
    return null;
  }
}
