import type { StyleSpec } from "./types";

const BASE: StyleSpec = {
  id: "base",
  name: "Base",
  mood: "Balanced",
  blurb: "",
  keywords: [],
  refs: ["m3", "gfonts", "wcag"],
  axes: { expressive: 40, sharp: 40, dark: 0, animated: 40, creative: 40, experimental: 20 },
  mode: "light",
  hue: 262,
  sat: 60,
  bgHue: 262,
  bgSat: 30,
  accentHue: 340,
  neutral: false,
  gradient: false,
  heading: "Inter",
  body: "Inter",
  mono: "JetBrains Mono",
  headingWeight: 700,
  tracking: -0.02,
  upper: false,
  scaleRatio: 1.25,
  baseSize: 16,
  lineHeight: 1.6,
  density: 40,
  container: 1120,
  radius: 12,
  shadow: "soft",
  border: "thin",
  glass: false,
  button: "solid",
  card: "elevated",
  nav: "bar",
  hero: "split",
  grid: "even",
  motion: "subtle",
  imagery: "photo",
  icon: "line",
  fix: { light: {}, dark: {} },
  locks: {},
};

type Patch = Partial<StyleSpec> & { id: string; name: string; mood: string; blurb: string };

const P = (p: Patch): StyleSpec => ({ ...BASE, ...p, axes: { ...BASE.axes, ...(p.axes || {}) }, fix: { light: {}, dark: {} }, locks: {} });

export const PRESETS: StyleSpec[] = [
  P({
    id: "minimal-modern", name: "Minimal Modern", mood: "Calm · precise", blurb: "Quiet neutrals, one confident accent, generous whitespace.",
    keywords: ["minimal", "clean", "simple", "modern", "calm"], refs: ["hig", "m3", "gfonts", "wcag"],
    hue: 230, sat: 55, bgHue: 230, bgSat: 12, accentHue: 190, heading: "Inter", body: "Inter", radius: 10, density: 30, shadow: "soft", motion: "subtle",
    axes: { expressive: 15, sharp: 40, dark: 0, animated: 30, creative: 25, experimental: 10 },
  }),
  P({
    id: "material-you", name: "Material You", mood: "Friendly · tonal", blurb: "Tonal containers, large corners and playful state layers.",
    keywords: ["material", "google", "android", "tonal", "friendly", "app"], refs: ["m3", "m3-type", "gfonts", "wcag"],
    hue: 265, sat: 45, bgHue: 265, bgSat: 40, accentHue: 25, heading: "Roboto", body: "Roboto", headingWeight: 500, tracking: 0, radius: 20, button: "pill", card: "soft", shadow: "soft", motion: "lively", density: 40,
    axes: { expressive: 55, sharp: 15, dark: 0, animated: 60, creative: 45, experimental: 20 },
  }),
  P({
    id: "swiss-editorial", name: "Swiss Editorial", mood: "Objective · rhythmic", blurb: "Strict grid, flush-left type, hairline rules, one signal color.",
    keywords: ["swiss", "grid", "typographic", "international", "poster", "objective"], refs: ["swiss", "editorial", "gfonts", "wcag"],
    neutral: true, hue: 4, sat: 85, bgHue: 40, bgSat: 6, accentHue: 4, heading: "Work Sans", body: "Work Sans", headingWeight: 700, tracking: -0.035, radius: 0, shadow: "none", border: "thin",
    card: "outlined", hero: "editorial", grid: "ruled", container: 1200, density: 55, motion: "none", imagery: "duotone",
    axes: { expressive: 45, sharp: 95, dark: 0, animated: 5, creative: 45, experimental: 40 },
  }),
  P({
    id: "luxury-premium", name: "Luxury Premium", mood: "Refined · exclusive", blurb: "Deep tones, hairline gold-like accents and slow, deliberate motion.",
    keywords: ["luxury", "premium", "elegant", "gold", "exclusive", "high-end", "boutique", "hotel"], refs: ["editorial", "hig", "gfonts", "wcag"],
    mode: "dark", hue: 42, sat: 52, bgHue: 30, bgSat: 12, accentHue: 30, heading: "Cormorant Garamond", body: "DM Sans", headingWeight: 700, tracking: 0.01, radius: 2, shadow: "layered", border: "thin",
    button: "outline", card: "outlined", density: 20, motion: "subtle", imagery: "duotone", container: 1180,
    axes: { expressive: 35, sharp: 80, dark: 90, animated: 25, creative: 45, experimental: 15 },
  }),
  P({
    id: "glassmorphism", name: "Glassmorphism", mood: "Airy · luminous", blurb: "Frosted layers floating over a soft aurora gradient.",
    keywords: ["glass", "frosted", "blur", "translucent", "aurora", "ios"], refs: ["refui", "hig", "gfonts", "wcag"],
    mode: "dark", hue: 250, sat: 85, bgHue: 255, bgSat: 55, accentHue: 190, gradient: true, glass: true, heading: "Outfit", body: "Outfit", radius: 24, shadow: "glow", card: "glass", nav: "glass", button: "gradient", motion: "lively", imagery: "geometric",
    axes: { expressive: 70, sharp: 10, dark: 85, animated: 60, creative: 65, experimental: 55 },
  }),
  P({
    id: "neo-brutalist", name: "Neo-Brutalist", mood: "Loud · honest", blurb: "Thick outlines, hard offset shadows, flat saturated color blocks.",
    keywords: ["brutal", "brutalist", "raw", "bold", "loud", "punk", "gumroad"], refs: ["brutalist", "awwwards", "gfonts", "wcag"],
    neutral: true, hue: 0, sat: 0, bgHue: 52, bgSat: 95, accentHue: 320, heading: "Space Grotesk", body: "Space Grotesk", headingWeight: 700, tracking: -0.03, radius: 0, shadow: "hard", border: "thick",
    button: "brutal", card: "brutal", nav: "brutal", motion: "lively", imagery: "geometric", density: 45,
    axes: { expressive: 90, sharp: 100, dark: 0, animated: 55, creative: 85, experimental: 80 },
  }),
  P({
    id: "soft-ui", name: "Soft UI", mood: "Tactile · gentle", blurb: "Pillowy surfaces, wide radii and whisper-soft depth.",
    keywords: ["soft", "neumorphism", "pillow", "gentle", "rounded", "wellness", "calm"], refs: ["hig", "m3", "gfonts", "wcag"],
    hue: 215, sat: 42, bgHue: 215, bgSat: 25, accentHue: 330, heading: "Nunito", body: "Nunito", radius: 28, shadow: "layered", card: "soft", button: "pill", density: 30, motion: "subtle",
    axes: { expressive: 30, sharp: 5, dark: 0, animated: 30, creative: 35, experimental: 15 },
  }),
  P({
    id: "bento-modern", name: "Bento Modern", mood: "Modular · playful", blurb: "Asymmetric tile grids, crisp borders and confident rounding.",
    keywords: ["bento", "tiles", "grid", "modular", "apple", "dashboard"], refs: ["hig", "awwwards", "gfonts", "wcag"],
    hue: 255, sat: 72, bgHue: 250, bgSat: 20, accentHue: 30, heading: "Sora", body: "Inter", radius: 22, grid: "bento", card: "outlined", shadow: "soft", border: "thin", motion: "lively", density: 35,
    axes: { expressive: 55, sharp: 30, dark: 0, animated: 55, creative: 60, experimental: 40 },
  }),
  P({
    id: "dark-ai", name: "Dark AI", mood: "Intelligent · electric", blurb: "Near-black canvas, electric violet glow and gradient highlights.",
    keywords: ["ai", "artificial", "intelligence", "dark", "futuristic", "llm", "startup", "premium ai", "agent"], refs: ["m3", "awwwards", "gfonts", "wcag"],
    mode: "dark", hue: 268, sat: 88, bgHue: 262, bgSat: 40, accentHue: 190, gradient: true, heading: "Space Grotesk", body: "Inter", radius: 14, shadow: "glow", card: "elevated", button: "gradient", motion: "lively", imagery: "geometric", hero: "centered",
    axes: { expressive: 65, sharp: 35, dark: 95, animated: 65, creative: 60, experimental: 55 },
  }),
  P({
    id: "cyberpunk", name: "Cyberpunk", mood: "Neon · dystopian", blurb: "Neon magenta and cyan on void black, angular type, kinetic motion.",
    keywords: ["cyber", "cyberpunk", "neon", "retro-future", "sci-fi", "synthwave", "gaming"], refs: ["awwwards", "gfonts", "wcag"],
    mode: "dark", hue: 322, sat: 100, bgHue: 265, bgSat: 45, accentHue: 178, heading: "Chakra Petch", body: "Chakra Petch", headingWeight: 700, tracking: 0.02, upper: true, radius: 2, shadow: "glow", border: "thin",
    button: "outline", card: "outlined", nav: "bar", motion: "kinetic", imagery: "grain", density: 55,
    axes: { expressive: 95, sharp: 90, dark: 100, animated: 90, creative: 85, experimental: 90 },
  }),
  P({
    id: "futuristic-enterprise", name: "Futuristic Enterprise", mood: "Trusted · advanced", blurb: "Ruled layouts, cool blues and precise data-dense components.",
    keywords: ["enterprise", "b2b", "platform", "cloud", "security", "infrastructure", "analytics"], refs: ["carbon", "m3", "gfonts", "wcag"],
    hue: 214, sat: 78, bgHue: 215, bgSat: 22, accentHue: 170, gradient: true, heading: "IBM Plex Sans", body: "IBM Plex Sans", radius: 6, shadow: "crisp", card: "outlined", grid: "ruled", density: 62, motion: "subtle", container: 1240,
    axes: { expressive: 35, sharp: 65, dark: 10, animated: 35, creative: 25, experimental: 30 },
  }),
  P({
    id: "japanese-minimal", name: "Japanese Minimal", mood: "Serene · spacious", blurb: "Ma — emptiness as structure, a single vermilion accent, quiet rhythm.",
    keywords: ["japanese", "zen", "muji", "wabi", "calm", "tea", "serene", "tokyo"], refs: ["japan", "hig", "gfonts", "wcag"],
    neutral: true, hue: 8, sat: 68, bgHue: 40, bgSat: 14, accentHue: 8, heading: "Zen Kaku Gothic New", body: "Zen Kaku Gothic New", headingWeight: 400, tracking: 0.05, radius: 0, shadow: "none", border: "thin", card: "flat", hero: "centered", density: 10, motion: "subtle", imagery: "duotone",
    axes: { expressive: 10, sharp: 70, dark: 0, animated: 15, creative: 40, experimental: 20 },
  }),
  P({
    id: "editorial-magazine", name: "Editorial Magazine", mood: "Literary · confident", blurb: "High-contrast serif headlines, column rules and long-form pacing.",
    keywords: ["editorial", "magazine", "journal", "blog", "publication", "news", "longform", "media"], refs: ["editorial", "swiss", "gfonts", "wcag"],
    hue: 14, sat: 72, bgHue: 40, bgSat: 20, accentHue: 14, heading: "Playfair Display", body: "Lora", headingWeight: 700, tracking: -0.02, scaleRatio: 1.333, radius: 0, shadow: "none", card: "flat", hero: "editorial", grid: "ruled", density: 40, motion: "subtle", imagery: "duotone",
    axes: { expressive: 60, sharp: 80, dark: 0, animated: 20, creative: 65, experimental: 35 },
  }),
  P({
    id: "creative-portfolio", name: "Creative Portfolio", mood: "Bold · personal", blurb: "Oversized display type, off-grid stacks and grainy imagery.",
    keywords: ["portfolio", "creative", "designer", "artist", "photographer", "studio", "personal"], refs: ["awwwards", "swiss", "gfonts", "wcag"],
    hue: 18, sat: 92, bgHue: 30, bgSat: 25, accentHue: 275, heading: "Bricolage Grotesque", body: "DM Sans", headingWeight: 700, tracking: -0.04, scaleRatio: 1.333, radius: 16, hero: "stack", shadow: "soft", motion: "kinetic", imagery: "grain", density: 30,
    axes: { expressive: 85, sharp: 40, dark: 0, animated: 80, creative: 95, experimental: 75 },
  }),
  P({
    id: "startup-saas", name: "Startup SaaS", mood: "Optimistic · fast", blurb: "Gradient CTAs, layered shadows, punchy headlines that convert.",
    keywords: ["saas", "startup", "landing", "product", "app", "software", "conversion", "b2c"], refs: ["m3", "hig", "gfonts", "wcag"],
    hue: 252, sat: 76, bgHue: 250, bgSat: 25, accentHue: 330, gradient: true, heading: "Manrope", body: "Inter", radius: 14, shadow: "layered", button: "gradient", card: "elevated", motion: "lively", density: 35,
    axes: { expressive: 60, sharp: 30, dark: 0, animated: 60, creative: 50, experimental: 25 },
  }),
  P({
    id: "corporate-professional", name: "Corporate Professional", mood: "Dependable · clear", blurb: "Conservative blues, compact rhythm, no-nonsense components.",
    keywords: ["corporate", "professional", "business", "consulting", "law", "agency", "formal", "company"], refs: ["carbon", "m3", "gfonts", "wcag"],
    hue: 212, sat: 68, bgHue: 212, bgSat: 14, accentHue: 32, heading: "Public Sans", body: "Public Sans", radius: 6, shadow: "crisp", card: "elevated", density: 55, motion: "none", imagery: "photo",
    axes: { expressive: 15, sharp: 60, dark: 0, animated: 10, creative: 5, experimental: 5 },
  }),
  P({
    id: "ecommerce-premium", name: "E-commerce Premium", mood: "Curated · tactile", blurb: "Serif display, warm neutrals and product-first, flat cards.",
    keywords: ["shop", "store", "ecommerce", "e-commerce", "fashion", "retail", "product", "brand", "boutique"], refs: ["editorial", "hig", "gfonts", "wcag"],
    neutral: true, hue: 20, sat: 30, bgHue: 30, bgSat: 18, accentHue: 350, heading: "DM Serif Display", body: "DM Sans", headingWeight: 400, tracking: -0.01, radius: 8, shadow: "soft", card: "flat", button: "solid", density: 32, motion: "subtle", imagery: "photo",
    axes: { expressive: 40, sharp: 45, dark: 0, animated: 30, creative: 55, experimental: 20 },
  }),
  P({
    id: "fintech", name: "Fintech", mood: "Secure · fresh", blurb: "Trustworthy teal-green, clear numerals and friendly precision.",
    keywords: ["fintech", "bank", "finance", "payments", "money", "crypto", "invest", "wallet", "insurance"], refs: ["carbon", "m3", "gfonts", "wcag"],
    hue: 166, sat: 72, bgHue: 170, bgSat: 18, accentHue: 250, gradient: true, heading: "Plus Jakarta Sans", body: "Plus Jakarta Sans", radius: 14, shadow: "soft", card: "elevated", button: "solid", density: 42, motion: "subtle",
    axes: { expressive: 35, sharp: 35, dark: 0, animated: 35, creative: 30, experimental: 20 },
  }),
  P({
    id: "developer-terminal", name: "Developer / Terminal", mood: "Technical · hacker", blurb: "Monospace everywhere, phosphor green on ink, ruled outlines.",
    keywords: ["developer", "terminal", "code", "cli", "devtools", "api", "hacker", "open source", "docs"], refs: ["carbon", "gfonts", "wcag"],
    mode: "dark", hue: 140, sat: 90, bgHue: 150, bgSat: 22, accentHue: 60, heading: "JetBrains Mono", body: "IBM Plex Mono", mono: "JetBrains Mono", headingWeight: 700, tracking: -0.02, radius: 2, shadow: "none", border: "thin", button: "outline", card: "outlined", grid: "ruled", density: 60, motion: "subtle", imagery: "grain",
    axes: { expressive: 30, sharp: 90, dark: 100, animated: 30, creative: 35, experimental: 45 },
  }),
  P({
    id: "organic-nature", name: "Organic Nature", mood: "Warm · grounded", blurb: "Earthy greens, soft blobs and a friendly serif voice.",
    keywords: ["nature", "organic", "eco", "green", "sustainable", "plant", "farm", "wellness", "yoga", "botanical"], refs: ["m3", "gfonts", "wcag"],
    hue: 138, sat: 34, bgHue: 85, bgSat: 30, accentHue: 24, heading: "Fraunces", body: "Nunito", headingWeight: 700, tracking: -0.01, radius: 26, shadow: "soft", card: "soft", button: "pill", density: 30, motion: "subtle", imagery: "illustration",
    axes: { expressive: 45, sharp: 10, dark: 0, animated: 30, creative: 55, experimental: 25 },
  }),
  P({
    id: "monochrome-wiki", name: "Monochrome Wikipedia-inspired", mood: "Neutral · encyclopedic", blurb: "Serif headings, ruled sections, and links as the only color.",
    keywords: ["wiki", "wikipedia", "encyclopedia", "documentation", "knowledge", "academic", "reference", "research"], refs: ["codex", "wm-style", "wp-mos", "gfonts", "wcag"],
    neutral: true, hue: 220, sat: 100, bgHue: 220, bgSat: 4, accentHue: 220, heading: "Libre Baskerville", body: "Source Sans 3", headingWeight: 400, tracking: 0, radius: 2, shadow: "none", border: "thin", card: "outlined", nav: "minimal", hero: "stack", grid: "ruled", container: 980, density: 48, motion: "none", imagery: "photo",
    axes: { expressive: 5, sharp: 70, dark: 0, animated: 0, creative: 5, experimental: 5 },
  }),
];

export const PRESET_BY_ID = Object.fromEntries(PRESETS.map((p) => [p.id, p]));
export const DEFAULT_SPEC = PRESETS[0];
